#ifndef TIRES_CONTROL_CFG_H_
#define TIRES_CONTROL_CFG_H_

#define MOTOR_FORWARD_PIN PINC4
#define MOTOR_BACKWARD_PIN PINC5
#define MOTOR_RIGHT_PIN PINC7
#define MOTOR_LEFT_PIN PINC6

#endif /* TIRES_CONTROL_CFG_H_ */
